### ISSUE TITLE
Wiktionary link should link to language

### ISSUE THREAD

**Issue by tbm** [longjiang/zerotohero-nuxt#1]
Looking up "pete" (Swahili for "ring") gives the right definition and a link to Wiktionary.  However, I think it would be best to link to the specific Wiktionary link and include the '#' for the language, i.e. it should link to https://en.wiktionary.org/wiki/pete#Swahili

See https://www.zerotohero.ca/en/sw/dictionary/wiktionary/8470

**Comment by longjiang** [comment]
Yeah this means I need to include a map of 8000 wiktionary language names ("Swahili") to their iso639-1 code ("sw"), I wonder if this convenience justifies the size of the download. But I might normalize my languages.csv.txt file so that the names of the languages match Wiktionary exactly. I'll see what I can do.

**Comment by longjiang** [comment]
Implemented in 5c2626071203e0f153f026e03967cd98716c4698
See https://www.zerotohero.ca/en/sw/dictionary/wiktionary/8470
